language: gcc

before_install:
  - export TGT='x86_64-w64-mingw32.shared'
  - export MXE_DIR=~/tmp/mxe
  - rm -rf $MXE_DIR
  - git clone --depth=1 https://github.com/mxe/mxe.git $MXE_DIR
  - sudo apt-get -y install autoconf automake autopoint bash bison bzip2 cmake flex gettext git g++ gperf intltool libffi-dev libtool libltdl-dev
    libssl-dev libxml-parser-perl make openssl patch perl pkg-config python ruby scons sed unzip wget xz-utils
  
script:
  - time make -C $MXE_DIR MXE_TARGETS="$TGT" pkgconf JOBS=4
  - time make -C $MXE_DIR MXE_TARGETS="$TGT" binutils JOBS=4
  - time make -C $MXE_DIR MXE_TARGETS="$TGT" gcc-gmp JOBS=4
  - time make -C $MXE_DIR MXE_TARGETS="$TGT" gcc-isl JOBS=4
  - time make -C $MXE_DIR MXE_TARGETS="$TGT" gcc-cloog JOBS=4
  - time make -C $MXE_DIR MXE_TARGETS="$TGT" gcc-mpfr JOBS=4
  - time make -C $MXE_DIR MXE_TARGETS="$TGT" gcc-mpc JOBS=4
  - time make -C $MXE_DIR MXE_TARGETS="$TGT" mingw-w64 JOBS=4
  - travis_wait 30 make -C $MXE_DIR MXE_TARGETS="$TGT" gcc JOBS=4

after_success:
  - ls -laR $MXE_DIR
  - cat $MXE_DIR/log/gcc
