os:
 - osx

env:
  
before_install:
  - brew update
  - brew update
  - brew audit --strict --online https://raw.githubusercontent.com/GoldenCheetah/GoldenCheetah/master/travis/libkml.rb
  - brew install --verbose https://raw.githubusercontent.com/GoldenCheetah/GoldenCheetah/master/travis/libkml.rb

script:
  - ls -laR /usr/local
