language: objective-c

before_install:
  - brew update
  - brew install qt

script:
  - brew install --verbose https://raw.github.com/gcoco/CI-for-GoldenCheetah/master/qwtplot3d.rb

after_success:
  - brew audit qwtplot3d
  - brew info qwtplot3d
