#language:
#  - cpp
#  
#compiler:
#  - gcc
os:
  - linux
  - osx
  
global:
  - BRANCH=master
  
env:
  - QT=qt4
  - QT=qt5

before_install:
  - OS=`uname`
  - echo $OS
  - if [ "$OS" = "Darwin" ];
    then
      brew update;
      brew install $QT;
      brew install https://raw.github.com/gcoco/CI-for-GoldenCheetah/master/qwtplot3d-$QT.rb;
    fi

before_script:

script:
  - if [ "$OS" = "Linux" ];
    then
      echo "Linux - " $QT;
    fi
  - cd GoldenCheetah
  - cp qwt/qwtconfig.pri.in qwt/qwtconfig.pri

after_script:
