language: objective-c

compiler:
#  - clang
  - gcc

env:
  - QT=qt4
  - QT=qt5
  
before_install:
  - brew install $QT

script:
  - git clone --depth 1 --branch Qt5.6 https://github.com/gcoco/qwtplot3d.git qwtplot3d
  - cd qwtplot3d
  - qmake -recursive
  - make -j3

after_script:
  - cd examples/bin
  - ldd axes

