language: objective-c

env:
  - FILE=qwtplot3d-0.3.1-qt5.rb
  
before_install:
  - brew update

script:
  - brew install  --verbose --debug https://raw.github.com/gcoco/CI-for-GoldenCheetah/master/$FILE

after_success:
  - brew audit https://raw.github.com/gcoco/CI-for-GoldenCheetah/master/$FILE
  - brew info https://raw.github.com/gcoco/CI-for-GoldenCheetah/master/$FILE
