language: objective-c

before_install:
  - brew update
  - brew install qt zlib

before_script:
  - brew create http://sourceforge.net/projects/qwtplot3d/files/qwtplot3d/0.2.7/qwtplot3d-0.2.7.tgz/download
  
script:
  - qmake -recursive CONFIG+=release

after_success:
