os:
 - osx

compiler:
  - clang
  - gcc

env:
  - QT_PATH=qt5 QT=qt5
  - QT_PATH=qt5 QT=qt5 QT_VER=5.5
  - QT_PATH=qt QT=qt4
  
before_install:
  - brew update
  - sh ./install-qt.sh
  
script:
  - git clone --depth 1 --branch Qt5.6 https://github.com/gcoco/qwtplot3d.git qwtplot3d
  - cd qwtplot3d
  - /usr/local/opt/$QT_PATH/bin/qmake -recursive DEFINES+=C++11
  - make -j3

after_script:
  - cd examples/bin
  - ls
  - otool -L ./axes
  - otool -L ./mesh

