language: cpp
compiler: gcc
sudo: none
dist: trusty
git:
  depth: 3
addons:
  apt:
    packages:
    - libglu1-mesa-dev
    - libgstreamer0.10-0
    - libgstreamer-plugins-base0.10-0
    - libssl-dev
    - libsamplerate0-dev
    - libpulse-dev
    - r-base-dev
    - libvlc-dev
    - libvlccore-dev
    - libusb-1.0-0-dev
    - libudev-dev
global:
  - secure: iqYW7f3//ZkMVzeCEarYn0S0DqKjFU9juBh0KF6WTlUsKX902Jtsk7dFoJlNDYBf63HLgV+wW2Hc6MxI9sGiUkom0gY9/To/aeGIJFGEX2sLm/e0Ok3qN521FA0Q/OiCFsD0RC6J+yrHxzI+rf8Z1rujceUsz2KgsrfAjYYv+BY=
  - secure: C6f58PXwvvHeVOjCLbyDRjgyF0tk+bXjCNUDur8VJLhJEGNdnrt+rH+d3azYaX0n348ZnQZ14as4M4rHjN1A/3DRbdUdOS7PQZrkj/n363ck1tvYOG/tzYqkEcVoQyjIJ7ZoTuBXDQry/VJmLxQjM0glTa2upNFHMOMwqZNkF+I=
  - secure: mgf181ok4rJTHxAdSaeIb/OzUx7PQc6UjJYfhJQcZDjN1Nou+Um6OHpnooMHeEq0CdGuLSiv2xVmuQnRjI5MfG5re/a3l39hSzi9tPLWi1y7uOLCtQFooJw3H+LhiKZcgAtEnkTmEhUCEu5uZ7cp4lWhrQZWCR5mCDNtJrGHjiw=
  - secure: UkW6SpgeACb6enGZADTAtPPRe23Tffne/SRQoBsZ3kGbKzgv8kTCLY0G5N71B1xEGdLB/36piOa0yji2SMW1jbflxR7tdOsiNpfd9R5qYqWVZRulY0qite8ZCwU5dqgy87pp4ECC1hNSOTq17aa4Sc4G4egg9AOy8cntLBTtxJA=
  - secure: rb/MKPHEK8yOK5uYpXq2o+MQ7h65ft+c/xE9XmLFk1jLnK0oxe6+KeoSFlQ0n5UwLSsHrytMXVaUHex6EEt0TheXFlohi7BcNFWRWXr+wLucuaPjMnU49VErrSigjJ5VW/rcR7fORmnDwn5y06r3Rer9SC1hImCxf/pqF8hFZps=
  - secure: FXJzm98lwbc1R2eh9/CvVReVRHEPLDm+sCRjiV9HJgeCveIUauLasp9Skamz0c6OKLmkjLY8JERPT491ZgCG8YcQ9x1bM8HGbmRqnn9xSUxINIRzVmyTiLMBoT/ibHHeFjFpyiGfukOAkHwMNNsrSrbaekhiJuekaXo7iTwYQB0=
  - secure: K9+6ufffQ2a6dCTwVSI5ZtrGE+JSsj2ZeQwJ8Xk/y1yhSlbnW6Uptfs5oZ4XJ/BAQbuKbctnczP/jwDtGBG/Y0WOxn8m1DYBrkeLeToc0JZ8dn2lF6H6BEcB3VI3iPUtxAXWHNeSCk2qaC83z80Ydjc5GCxoAOwlw5/BEsRYI/s=
  - secure: n6khzr3bPnvh2lTE1NmcaPWRWkqLBUcXZL20EO0Q0HyhH2O22fwsKfnODCDtP1UEQxW+E0G3DkedSz/RmpMWbv1KpWKNNKl74wIdUE53nRIBLTULRoypCq1tDZzQqkoogbXu3pWrb23YoUuM2p5zxM9l3TiNbcrdZeQ+PInVL6o=
  - secure: mJEJUwt1jhx5qx5h5C8gnYJyaUb5fItSJGU/Tgp0IMCPCUSXtjHf9QTKITAKvg/hY8zggSwo+Vg2VzdMypdxDKqAeH/xAjq/o1+4linWphSjWpUGTqF/B8sR37WtduXtetamX+ctsbG4I77Xw+7y8OPPoCPxDct9hWxfCw6eBrI=
  - secure: BX7lVlMs6c6qOCMc7Eu0s3G7/es+3h/EGElS/4wjw4/nxp91bd0RbkOmGmgEKOFw5XRFl8gV0kEzmFhrJTdGfTnWHmdsGjSo2VzwePgW/PbDdQrTVD2rYBmmPoeTXf3S3v0P7d3pBrpuxAqkmj7bFkpnvviCN9erC4bUhSg6jEI=
  - secure: AC6pelym0R1Pq6GgcAy7E/BmlNWrni+41P8V8PMtjBKEtiyJ3tQa+KCn5g0UfGzktRHk+0l+szz3Wdy+bzl+ifiJVhXXs95B9F9El03p33UQLFPi+wFlivddP5DLc+4vIsDUiaNX97p89vo1/R96OLjpF1mUzfOMKYmAiMGP/Co=
  - secure: QXyyyutxesRVae/WFi75dxlNw2qTyWc6WQ3vmRER9BFhlrNtt8lmE+M6ghMDOhxigzSXWxHcG9r66BLOw4DML7AXg4f3NIAIYuYQrpfsWQ1TKGC/vVvIPDlNBKL62zSOoNowjup1HfZpB575wl4JkmHjoMPDfQ4yM/JVR+MKmIM=
  - secure: lefpL3SB8yN0Vn1R2e0hAFpJgFnu4rJ/vn7DucSKQvJ61K7t3LrUHFXElDQGFZMbytx4OJDeYsJtrccrIHjcsSAEIyW8TTcwn5/JopnyeQ3ukV5AYpEoQusym09XKru9E7awqvnZrXz6mdoIum5JP7+H116mPN4vsvz5nkNWxeg=
  - secure: RAGPq/thN9x6STNueDbeJWGUN75OLNcUVUkLHI/eZwPrkMaiQPfxIaJ+8eO2PszDcBojw3eYVhzbRvLnLiXmHL3buwD6oXMTyYnxGzCZ61DeDQ2cQa8ynKmRim5JL3viKMqtdyasXVoGf/u0GqMsgaLcqN6e/vXuXMGu6kkUPEQ=
env:
# Set HTML=WEBKIT to use WEBKIT or HTML=WEBENGINE to use WEBENGINE.
#  - HTML=WEBKIT QTMAX=5.5 QTMin=1
#  - HTML=WEBKIT QTMAX=5.6 QTMin=0
#  - HTML=WEBKIT QTMAX=5.7 QTMin=1
  - HTML=WEBENGINE QTMAX=5.8 QTMin=0
before_install:
  - export QTPATH=${TRAVIS_BUILD_DIR}/Qt${QTMAX}.${QTMin}/${QTMAX}/gcc_64
  - export QT_SELECT=qt5
  - cd ${TRAVIS_BUILD_DIR}
  - wget https://github.com/gcoco/Qt-Ubuntu-64bit/releases/download/QT${QTMAX}.${QTMin}/Qt${QTMAX}.${QTMin}.tar.gz
  - tar xzf Qt${QTMAX}.${QTMin}.tar.gz
  - wget https://github.com/gcoco/Qt-Ubuntu-64bit/releases/download/QT5.8.0/Qt${QTMAX}.${QTMin}-gc-libs.tar.gz -O ${TRAVIS_BUILD_DIR}/gc-libs.tar.gz
  - tar xzf ${TRAVIS_BUILD_DIR}/gc-libs.tar.gz
  #- sudo apt-get install -qq libglu1-mesa-dev libgstreamer0.10-0 libgstreamer-plugins-base0.10-0
  #- sudo apt-get install -qq libssl-dev libsamplerate0-dev libpulse-dev r-base-dev
  #- sudo apt-get install -qq libvlc-dev libvlccore-dev
  #- sudo apt-get install -qq libusb-1.0-0-dev libudev-dev
before_script:
  - mkdir -p ${TRAVIS_BUILD_DIR}/usr/{lib,include}
  - chmod u+x travis/$TRAVIS_OS_NAME/*.sh
  # FD2XX Install
  #- ${TRAVIS_BUILD_DIR}/travis/$TRAVIS_OS_NAME/install-ftd2xx.sh
  # QWTPLOT3D build
  #- ${TRAVIS_BUILD_DIR}/travis/$TRAVIS_OS_NAME/install-qwtplot3d.sh
  # SRMIO build 
  #- ${TRAVIS_BUILD_DIR}/travis/$TRAVIS_OS_NAME/install-srmio.sh
  # libkml build
  #- ${TRAVIS_BUILD_DIR}/travis/$TRAVIS_OS_NAME/install-libkml.sh
  # libical build
  #- ${TRAVIS_BUILD_DIR}/travis/$TRAVIS_OS_NAME/install-libical.sh
  # libusb-compat build
  #- ${TRAVIS_BUILD_DIR}/travis/$TRAVIS_OS_NAME/install-libusb-compat.sh
  # libusb-compat build
  #- ${TRAVIS_BUILD_DIR}/travis/$TRAVIS_OS_NAME/install-lmfit.sh
  # Setup GoldenCheetah
  - cd ${TRAVIS_BUILD_DIR}
  - git clone --depth 1 git://github.com/GoldenCheetah/GoldenCheetah.git
  - cd GoldenCheetah
  - export GC_COMMIT=`git rev-parse HEAD | cut -c 1-10`
  - export GC_DATE=`git log -1 --date=iso --format=fuller | egrep ^CommitDate | cut -c 13-22`
  - export GC_INFO=${GC_DATE}':master@'${GC_COMMIT}
  - git am ${TRAVIS_BUILD_DIR}/0001-For-qwtplot3d-fix.patch
  - cp qwt/qwtconfig.pri.in qwt/qwtconfig.pri
  - cp src/gcconfig.pri.in src/gcconfig.pri
  - echo DEFINES += GC_VERSION=\\\\\\\"${GC_INFO}\\\\\\\" >> src/gcconfig.pri
  - echo QMAKE_LFLAGS += \"-Wl,-rpath,\\\'\\$\$ORIGIN/lib\\\'\" >> src/gcconfig.pri
  - if [[ "$HTML" == "WEBENGINE" ]]; then echo DEFINES += NOWEBKIT >> src/gcconfig.pri; fi
  - sed -i "s|#\(CONFIG += release.*\)|\1 static|" src/gcconfig.pri
  - sed -i "s|#\(QMAKE_LRELEASE = \).*|\1 ${QTPATH}/bin/lrelease|" src/gcconfig.pri
  - sed -i "s|^#QMAKE_CXXFLAGS|QMAKE_CXXFLAGS|" src/gcconfig.pri
  - sed -i "s|#\(SRMIO_INSTALL =.*\)|\1 ${TRAVIS_BUILD_DIR}/usr|" src/gcconfig.pri
  - sed -i "s|#\(D2XX_INCLUDE =.*\)|\1 ${TRAVIS_BUILD_DIR}/usr/include|" src/gcconfig.pri
  - sed -i "s|#\(QWT3D_INSTALL =.*\)|\1 ${TRAVIS_BUILD_DIR}/usr|" src/gcconfig.pri
  - sed -i "s|#\(KML_INSTALL =\).*|\1 ${TRAVIS_BUILD_DIR}/usr|" src/gcconfig.pri
  - sed -i "s|#\(ICAL_INSTALL =.*\)|\1 ${TRAVIS_BUILD_DIR}/usr|" src/gcconfig.pri
  - sed -i "s|#\(ICAL_INCLUDE =.*\)|\1 ${TRAVIS_BUILD_DIR}/usr/include/libical|" src/gcconfig.pri
  - sed -i "s|#\(ICAL_LIBS    =.*\)|\1 ${TRAVIS_BUILD_DIR}/usr/lib/libical.a ${TRAVIS_BUILD_DIR}/usr/lib/libicalss.a ${TRAVIS_BUILD_DIR}/usr/lib/libicalvcal.a|" src/gcconfig.pri
  - sed -i "s|#\(LMFIT_INSTALL =\).*|\1 ${TRAVIS_BUILD_DIR}/usr|" src/gcconfig.pri
  - sed -i "s|#\(LIBUSB_INSTALL =\).*|\1 ${TRAVIS_BUILD_DIR}/usr|" src/gcconfig.pri
  - sed -i "s|#\(LIBUSB_LIBS    =.*\)|\1 ${TRAVIS_BUILD_DIR}/usr/lib/libusb.a -lusb-1.0 -ldl -ludev|" src/gcconfig.pri
  - sed -i "s|#\(VLC_INSTALL =.*\)|\1 /usr|" src/gcconfig.pri
  - sed -i "s|#\(VLC_LIBS    =.*\)|\1 -lvlc -lvlccore|" src/gcconfig.pri
  - sed -i "s|#\(SAMPLERATE_INSTALL =\).*|\1 /usr|" src/gcconfig.pri
  - sed -i "s|#\(SAMPLERATE_LIBS =\).*|\1 -lsamplerate|" src/gcconfig.pri
  - sed -i "s|^#LIBZ_LIBS|LIBZ_LIBS|" src/gcconfig.pri
  - sed -i "s|^#HTPATH|HTPATH|" src/gcconfig.pri
  - sed -i "s|\(DEFINES += GC_VIDEO_NONE.*\)|#\1 |" src/gcconfig.pri
  - sed -i "s|#\(DEFINES += GC_VIDEO_VLC.*\)|\1|" src/gcconfig.pri
  - sed -i "s|#\(DEFINES += GC_WANT_R.*\)|\1|" src/gcconfig.pri
  - sed -i "s/__GC_GOOGLE_CALENDAR_CLIENT_SECRET__/"$GC_GOOGLE_CALENDAR_CLIENT_SECRET"/" src/Core/Secrets.h
  - sed -i "s/__GC_STRAVA_CLIENT_SECRET__/"$GC_STRAVA_CLIENT_SECRET"/" src/Core/Secrets.h
  - sed -i "s/__GC_DROPBOX_CLIENT_SECRET__/"$GC_DROPBOX_CLIENT_SECRET"/" src/Core/Secrets.h
  - sed -i "s/__GC_CYCLINGANALYTICS_CLIENT_SECRET__/"$GC_CYCLINGANALYTICS_CLIENT_SECRET"/" src/Core/Secrets.h
  - sed -i "s/__GC_TWITTER_CONSUMER_SECRET__/"$GC_TWITTER_CONSUMER_SECRET"/" src/Core/Secrets.h
  - sed -i "s/__GC_DROPBOX_CLIENT_ID__/"$GC_DROPBOX_CLIENT_ID"/" src/Core/Secrets.h
  - sed -i "s/__GC_MAPQUESTAPI_KEY__/"$GC_MAPQUESTAPI_KEY"/" src/Core/Secrets.h
  - sed -i "s/__GC_CLOUD_DB_BASIC_AUTH__/"$GC_CLOUD_DB_BASIC_AUTH"/" src/Core/Secrets.h
  - sed -i "s/__GC_CLOUD_DB_APP_NAME__/"$GC_CLOUD_DB_APP_NAME"/" src/Core/Secrets.h
  - sed -i "s/__GC_GOOGLE_DRIVE_CLIENT_ID__/"$GC_GOOGLE_DRIVE_CLIENT_ID"/" src/Core/Secrets.h
  - sed -i "s/__GC_GOOGLE_DRIVE_CLIENT_SECRET__/"$GC_GOOGLE_DRIVE_CLIENT_SECRET"/" src/Core/Secrets.h
  - sed -i "s/__GC_GOOGLE_DRIVE_API_KEY__/"$GC_GOOGLE_DRIVE_API_KEY"/" src/Core/Secrets.h
  - sed -i "s/__GC_TODAYSPLAN_CLIENT_SECRET__/"$GC_TODAYSPLAN_CLIENT_SECRET"/" src/Core/Secrets.h
  - cat src/gcconfig.pri
  - ${QTPATH}/bin/lupdate src/src.pro

script:
  - ${QTPATH}/bin/qmake -recursive
  - make --silent -j3 || make

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - cp ${TRAVIS_BUILD_DIR}/GoldenCheetah/src/GoldenCheetah ${TRAVIS_BUILD_DIR}/build/opt/GoldenCheetah/GoldenCheetah
  - cp -R ${QTPATH}/{libexec,lib,plugins,resources,translations} ${TRAVIS_BUILD_DIR}/build/opt/GoldenCheetah/
  - cd ${TRAVIS_BUILD_DIR}/build/opt/GoldenCheetah
  - chmod u+x GoldenCheetah
  - ./GoldenCheetah --version || ldd GoldenCheetah
  - cd ${TRAVIS_BUILD_DIR}
  - export SIZE=`ls -l --block-size=1kB ${TRAVIS_BUILD_DIR}/GoldenCheetah/src/GoldenCheetah | cut -d " " -f5`
  - sed -i 's/SIZE/'"$SIZE"'/g' ${TRAVIS_BUILD_DIR}/build/DEBIAN/control
  - cp ${TRAVIS_BUILD_DIR}/GoldenCheetah/src/Resources/linux/51-garmin-usb.rules ${TRAVIS_BUILD_DIR}/build/etc/udev/rules.d/
  - export VERSION="3.5.0dev+`date +%Y%m%d`"
  - sed -i 's/VERSION/'"$VERSION"'/g' ${TRAVIS_BUILD_DIR}/build/DEBIAN/control
#  - cat ${TRAVIS_BUILD_DIR}/build/DEBIAN/control
  - dpkg -b ${TRAVIS_BUILD_DIR}/build/ ${TRAVIS_BUILD_DIR}/GoldenCheetah_${VERSION}_${HTML}_amd64.deb
  - dpkg -c ${TRAVIS_BUILD_DIR}/GoldenCheetah_${VERSION}_${HTML}_amd64.deb
#  - ls -l ${TRAVIS_BUILD_DIR}/GoldenCheetah_${VERSION}_${HTML}_amd64.deb
  
deploy:
  provider: releases
  api_key:
    secure: GI+6glvv5Bq7mr8eEab/P+Wq6RzKq5QVCQ+8bWzJ3DqhAkter09jhwOXmBVCUgano2mNGsNrcnyAY/sQyGcnm5IEpdzXYlOQeUfww47OyiS4ECAxLDVLp2/fo8KHuKDJIs7aw/vBnqh3R5vkaZOMfePL5/SgwOL7nNzS5seYN6Y=
  file: '${TRAVIS_BUILD_DIR}/GoldenCheetah_${VERSION}_${HTML}_amd64.deb'
#  file: '${TRAVIS_BUILD_DIR}/gc-libs.tar.gz'
  skip_cleanup: true
  on:
    tags: true
    cron: true
    repo: gcoco/CI-for-GoldenCheetah
 
