language: objective-c

before_install:
  - brew update
  - brew install qt

before_script:
  - brew create http://downloads.sourceforge.net/sourceforge/qwtplot3d/qwtplot3d-0.2.7.tgz
  
script:
  - qmake -recursive CONFIG+=release

after_success:
