language: objective-c

before_install:
  - brew update
#  - brew install qt

script:
  - brew install --verbose --debug https://raw.github.com/gcoco/CI-for-GoldenCheetah/master/libkml.rb

after_success:
  - brew audit https://raw.github.com/gcoco/CI-for-GoldenCheetah/master/libkml.rb
  - brew info https://raw.github.com/gcoco/CI-for-GoldenCheetah/master/libkml.rb
