language: objective-c

before_install:
  - brew update
#  - brew install qt

script:
  - brew install --verbose --debug --HEAD https://raw.github.com/gcoco/CI-for-GoldenCheetah/master/libkml.rb

after_success:
  - ls -laR /usr/local/Cellar/libkml
  - otool -fahlL /usr/local/lib/libkml*
  - lipo -info /usr/local/lib/libkml*
  - brew audit https://raw.github.com/gcoco/CI-for-GoldenCheetah/master/libkml.rb
  - brew info https://raw.github.com/gcoco/CI-for-GoldenCheetah/master/libkml.rb
