os:
 - osx

env:
  
before_install:
  - brew update
#  - sh ./install-qt.sh
  - brew tap homebrew/science
  - brew install --verbose https://raw.githubusercontent.com/gcoco/CI-for-GoldenCheetah/master/lmfit.rb

script:
  - ls -laR /usr/local
