language: objective-c

compiler:
#  - clang
  - gcc

env:
  - QT=4
  - QT=5
  
before_install:
  - brew install $QT

script:
  git clone --depth 1 --branch Qt5.6 https://github.com/gcoco/qwtplot3d.git qwtplot3d
  cd qwtplot3d
  qmake -recursive
  make -j3

