#language:
#  - cpp
#  
#compiler:
#  - gcc
os:
  - linux
  - osx
  
global:
  - BRANCH=master
  
env:
  - QT=qt4
  - QT=qt5

before_install:
  - OS=`uname`
  - echo $OS

before_script:

script:
  - if [ "$OS" = "Darwin" ];
    then
      echo "Darwin - " $QT;
    fi
  - if [ "$OS" = "Linux" ];
    then
      echo "Linux - " $QT;
    fi
  
after_script:
