before_install:
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install flex bison qt4-qmake qt4-dev-tools libqt4-dev
    liboauth-dev libqwtplot3d-qt4-dev libical-dev libusb-dev libvlc-dev libvlccore-dev libclucene-dev

before_script:
  - git clone --depth 1 git://github.com/GoldenCheetah/GoldenCheetah.git
  - cd GoldenCheetah && pwd
  - cp qwt/qwtconfig.pri.in qwt/qwtconfig.pri
  - cp src/gcconfig.pri.in src/gcconfig.pri
  - ls -la
  - lupdate-qt4 src/src.pro
  - sed -i "s|#\(LIBOAUTH_INSTALL =.*\)|\1 /usr|" src/gcconfig.pri
  - sed -i "s|#\(LIBOAUTH_LIBS =.*\)|\1 -loauth|" src/gcconfig.pri
  - sed -i "s|#\(QWT3D_INSTALL =.*\)|\1 /usr|" src/gcconfig.pri
  - sed -i "s|#\(QWT3D_INCLUDE =.*\)|\1 /usr/include/qwtplot3d-qt4|" src/gcconfig.pri
  - sed -i "s|#\(QWT3D_LIBS =.*\)|\1 -lqwtplot3d-qt4|" src/gcconfig.pri
  - sed -i "s|#\(ICAL_INSTALL =.*\)|\1 /usr|" src/gcconfig.pri
  - sed -i "s|#\(ICAL_LIBS =.*\)|\1 -lical|" src/gcconfig.pri
  - sed -i "s|#\(LIBUSB_INSTALL =\).*|\1 /usr|" src/gcconfig.pri
  - sed -i "s|#\(LIBUSB_LIBS =.*\)|\1 -lusb|" src/gcconfig.pri
  - sed -i "s|#\(VLC_INSTALL =.*\)|\1 /usr|" src/gcconfig.pri
  - sed -i "s|#\(VLC_LIBS =.*\)|\1 -lvlc -lvlccore|" src/gcconfig.pri
  - sed -i "s|#\(CLUCENE_INCLUDE =\).*|\1 /usr/include/CLucene /usr/lib|" src/gcconfig.pri
  - sed -i "s|#\(CLUCENE_LIBS =\).*|\1 -lclucene|" src/gcconfig.pri
  - sed -i "s|#\(CONFIG += link_pkgconfig\)|\1|" src/gcconfig.pri
  - sed -i "s|#\(PKGCONFIG = .*\)|\1 oauth libical libusb libvlc vlc-plugin|" src/gcconfig.pri
  - cat src/gcconfig.pri
  
script:
  - pwd
  - qmake-qt4 -recursive CONFIG+=release
  - make -j4
  
after_success:
  - ldd src/GoldenCheetah
  - src/GoldenCheetah --version
