language: cpp
compiler: gcc
sudo: required
dist: trusty
git:
  depth: 3
global:
  - secure: iqYW7f3//ZkMVzeCEarYn0S0DqKjFU9juBh0KF6WTlUsKX902Jtsk7dFoJlNDYBf63HLgV+wW2Hc6MxI9sGiUkom0gY9/To/aeGIJFGEX2sLm/e0Ok3qN521FA0Q/OiCFsD0RC6J+yrHxzI+rf8Z1rujceUsz2KgsrfAjYYv+BY=
  - secure: C6f58PXwvvHeVOjCLbyDRjgyF0tk+bXjCNUDur8VJLhJEGNdnrt+rH+d3azYaX0n348ZnQZ14as4M4rHjN1A/3DRbdUdOS7PQZrkj/n363ck1tvYOG/tzYqkEcVoQyjIJ7ZoTuBXDQry/VJmLxQjM0glTa2upNFHMOMwqZNkF+I=
  - secure: mgf181ok4rJTHxAdSaeIb/OzUx7PQc6UjJYfhJQcZDjN1Nou+Um6OHpnooMHeEq0CdGuLSiv2xVmuQnRjI5MfG5re/a3l39hSzi9tPLWi1y7uOLCtQFooJw3H+LhiKZcgAtEnkTmEhUCEu5uZ7cp4lWhrQZWCR5mCDNtJrGHjiw=
  - secure: UkW6SpgeACb6enGZADTAtPPRe23Tffne/SRQoBsZ3kGbKzgv8kTCLY0G5N71B1xEGdLB/36piOa0yji2SMW1jbflxR7tdOsiNpfd9R5qYqWVZRulY0qite8ZCwU5dqgy87pp4ECC1hNSOTq17aa4Sc4G4egg9AOy8cntLBTtxJA=
  - secure: rb/MKPHEK8yOK5uYpXq2o+MQ7h65ft+c/xE9XmLFk1jLnK0oxe6+KeoSFlQ0n5UwLSsHrytMXVaUHex6EEt0TheXFlohi7BcNFWRWXr+wLucuaPjMnU49VErrSigjJ5VW/rcR7fORmnDwn5y06r3Rer9SC1hImCxf/pqF8hFZps=
  - secure: FXJzm98lwbc1R2eh9/CvVReVRHEPLDm+sCRjiV9HJgeCveIUauLasp9Skamz0c6OKLmkjLY8JERPT491ZgCG8YcQ9x1bM8HGbmRqnn9xSUxINIRzVmyTiLMBoT/ibHHeFjFpyiGfukOAkHwMNNsrSrbaekhiJuekaXo7iTwYQB0=
env:
  - WEBKIT=1
#  - WEBKIT=0
before_install:
  - export QT_SELECT=qt5
#  - date
#  - sudo apt-get update -qq
#  - sudo apt-get install -qq build-essential cmake flex bison
#  - sudo apt-get install -qq qt5-default qttools5-dev-tools
#  - sudo apt-get install -qq libqt5svg5-dev qtmultimedia5-dev libqt5serialport5-dev
  - if [[ "$WEBKIT" == "1" ]]; then sudo apt-get install -qq libqt5webkit5-dev; fi
#  - if [[ "$WEBKIT" == "0" ]]; then sudo apt-get install -qq libqt5webengine5-dev; fi
  - wget https://github.com/gcoco/Qt5.5.1-Ubuntu14.04-64bit/releases/download/v1.0/Qt5.5.1.tar.gz
  - tar xf Qt5.5.1.tar.gz
  - sudo apt-get install -qq libgstreamer0.10-0 libgstreamer-plugins-base0.10-0
  - sudo apt-get install -qq libssl-dev libsamplerate0-dev
  - sudo apt-get install -qq libvlc-dev libvlccore-dev
before_script:
  - chmod u+x travis/$TRAVIS_OS_NAME/*.sh
  # QWTPLOT3D build
  - ./travis/$TRAVIS_OS_NAME/install-qwtplot3d.sh
  # SRMIO build 
  - ./travis/$TRAVIS_OS_NAME/install-srmio.sh
  # libkml build
  - ./travis/$TRAVIS_OS_NAME/install-libkml.sh
  # libical build
  - ./travis/$TRAVIS_OS_NAME/install-libical.sh
  # libusb-compat build
  - ./travis/$TRAVIS_OS_NAME/install-libusb-compat.sh
  # Setup GoldenCheetah
  - git clone --depth 1 git://github.com/GoldenCheetah/GoldenCheetah.git
  - cd GoldenCheetah
  - export GC_COMMIT=`git rev-parse HEAD | cut -c 1-10`
  - export GC_DATE=`git log -1 --date=iso --format=fuller | egrep ^CommitDate | cut -c 13-22`
  - export GC_INFO=${GC_DATE}':master@'${GC_COMMIT}
  - cp qwt/qwtconfig.pri.in qwt/qwtconfig.pri
  - cp src/gcconfig.pri.in src/gcconfig.pri
  - echo DEFINES += GC_VERSION=\\\\\\\"${GC_INFO}\\\\\\\" >> src/gcconfig.pri
#  - if [[ "$WEBKIT" == "0" ]]; then echo DEFINES += NOWEBKIT >> src/gcconfig.pri; fi
  - sed -i "s|#\(CONFIG += release.*\)|\1 static|" src/gcconfig.pri
  - sed -i "s|#\(QMAKE_LRELEASE = \).*|\1 ../../Qt5.5.1/5.5/gcc_64/bin/lrelease|" src/gcconfig.pri
  - sed -i "s|^#QMAKE_CXXFLAGS|QMAKE_CXXFLAGS|" src/gcconfig.pri
  - sed -i "s|#\(SRMIO_INSTALL =.*\)|\1 ../../usr|" src/gcconfig.pri
  - sed -i "s|#\(QWT3D_INSTALL =.*\)|\1 ../../qwtplot3d|" src/gcconfig.pri
  - sed -i "s|#\(KML_INSTALL =\).*|\1 ../../usr|" src/gcconfig.pri
  - sed -i "s|#\(ICAL_INSTALL =.*\)|\1 ../../usr|" src/gcconfig.pri
  - sed -i "s|#\(ICAL_LIBS    =.*\)|\1 ../../usr/lib/libical.a|" src/gcconfig.pri
  - sed -i "s|#\(LIBUSB_INSTALL =\).*|\1 ../../usr|" src/gcconfig.pri
  - sed -i "s|#\(LIBUSB_LIBS    =.*\)|\1 ../../usr/lib/libusb.a -lusb-1.0 -ldl -ludev|" src/gcconfig.pri
  - sed -i "s|#\(VLC_INSTALL =.*\)|\1 /usr|" src/gcconfig.pri
  - sed -i "s|#\(VLC_LIBS    =.*\)|\1 -lvlc -lvlccore|" src/gcconfig.pri
  - sed -i "s|#\(SAMPLERATE_INSTALL =\).*|\1 /usr|" src/gcconfig.pri
  - sed -i "s|#\(SAMPLERATE_LIBS =\).*|\1 -lsamplerate|" src/gcconfig.pri
  - sed -i "s|^#LIBZ_LIBS|LIBZ_LIBS|" src/gcconfig.pri
  - sed -i "s|^#HTPATH|HTPATH|" src/gcconfig.pri
  - sed -i "s|\(DEFINES += GC_VIDEO_NONE.*\)|#\1 |" src/gcconfig.pri
  - sed -i "s|#\(DEFINES += GC_VIDEO_VLC.*\)|\1|" src/gcconfig.pri
  - sed -i "s/__GC_GOOGLE_CALENDAR_CLIENT_SECRET__/"$GC_GOOGLE_CALENDAR_CLIENT_SECRET"/" src/Core/Secrets.h
  - sed -i "s/__GC_STRAVA_CLIENT_SECRET__/"$GC_STRAVA_CLIENT_SECRET"/" src/Core/Secrets.h
  - sed -i "s/__GC_DROPBOX_CLIENT_SECRET__/"$GC_DROPBOX_CLIENT_SECRET"/" src/Core/Secrets.h
  - sed -i "s/__GC_CYCLINGANALYTICS_CLIENT_SECRET__/"$GC_CYCLINGANALYTICS_CLIENT_SECRET"/" src/Core/Secrets.h
  - sed -i "s/__GC_TWITTER_CONSUMER_SECRET__/"$GC_TWITTER_CONSUMER_SECRET"/" src/Core/Secrets.h
  - cat src/gcconfig.pri
  - ../Qt5.5.1/5.5/gcc_64/bin/lupdate src/src.pro

script:
  - ../Qt5.5.1/5.5/gcc_64/bin/qmake -recursive
  - make -j3 V=0

after_success:
  - ldd src/GoldenCheetah
  - src/GoldenCheetah --version
  - cd ..
  - cp GoldenCheetah/src/GoldenCheetah build/opt/GoldenCheetah/GoldenCheetah
  - export SIZE=`ls -l --block-size=1kB GoldenCheetah/src/GoldenCheetah | cut -d " " -f5`
  - sed -i 's/SIZE/'"$SIZE"'/g' build/DEBIAN/control
  - cp GoldenCheetah/src/Resources/linux/51-garmin-usb.rules build/etc/udev/rules.d/
  - export VERSION="4.0.0dev+`date +%Y%m%d`"
  - sed -i 's/VERSION/'"$VERSION"'/g' build/DEBIAN/control
  - cat build/DEBIAN/control
  - dpkg -b build/ GoldenCheetah_${VERSION}_amd64.deb
  - dpkg -c GoldenCheetah_${VERSION}_amd64.deb
  
deploy:
  provider: releases
  api_key:
    secure: GI+6glvv5Bq7mr8eEab/P+Wq6RzKq5QVCQ+8bWzJ3DqhAkter09jhwOXmBVCUgano2mNGsNrcnyAY/sQyGcnm5IEpdzXYlOQeUfww47OyiS4ECAxLDVLp2/fo8KHuKDJIs7aw/vBnqh3R5vkaZOMfePL5/SgwOL7nNzS5seYN6Y=
  file: 'GoldenCheetah_${VERSION}_amd64.deb'
  skip_cleanup: true
  on:
    tags: true
    repo: gcoco/CI-for-GoldenCheetah
    branch: Linux-QT5

