os:
  - linux
  - osx
  
env:
  - QT=4
  - QT=5

before_install:
  - git clone --depth=1 https://github.com/GoldenCheetah/GoldenCheetah.git
  - cd GoldenCheetah
  - pwd
  - sh travis-ci/$TRAVIS_OS_NAME/before_install_QT$QT.sh $TRAVIS_OS_NAME $QT
  - sh travis-ci/$TRAVIS_OS_NAME/before_install_QT$QT.sh $TRAVIS_OS_NAME $QT

before_script:
  - sh travis-ci/$TRAVIS_OS_NAME/before_script_QT$QT.sh $TRAVIS_OS_NAME $QT

script:
  - sh travis-ci/$TRAVIS_OS_NAME/script_QT$QT.sh $TRAVIS_OS_NAME $QT

after_success:
  - sh travis-ci/$TRAVIS_OS_NAME/after_success_$QT.sh $TRAVIS_OS_NAME $QT
