#language:
#  - cpp
#  
#compiler:
#  - gcc
os:
  - linux
  - osx
  
global:
  - BRANCH=master QT=qt4
  - BRANCH=master QT=qt5

before_install:
  - OS=`uname`
  - echo $OS

before_script:

script:
  echo $BRANCH
  echo $QT
  
  
after_script:
