#commit: d00ac93fb23f88b3b6aaf8b9edadaf66336ba9aa
branches:
  only:
    - master
    - Mac

language: 
  - objective-c
  
compiler:
  - clang
  
env:
    - BRANCH=master QT=qt5 QT_PATH=qt5
    - BRANCH=master QT=qt4 QT_PATH=qt

before_install:
  - brew update
  - brew install $QT --use-clang
  - brew install liboauth libical libusb libusb-compat boost pkgconfig srmio --use-clang
  - brew install https://raw.github.com/gcoco/homebrew/clucene-2.3.3.4/Library/Formula/clucene.rb --use-clang
  # Have to get qwtplot3d into homebrew and support Qt4 and Qt5.
  - brew install https://raw.github.com/gcoco/CI-for-GoldenCheetah/master/qwtplot3d-$QT.rb --use-clang
  #- brew install libkml --HEAD
  - brew install --HEAD https://raw.github.com/gcoco/CI-for-GoldenCheetah/master/libkml.rb --use-clang
  # Need to set +w on brew files or macdeployqt fails
  - sudo chmod -R +w /usr/local
  - curl -O http://www.ftdichip.com/Drivers/D2XX/MacOSX/D2XX1.2.2.dmg
  - hdiutil mount D2XX1.2.2.dmg
  
before_script:
  - date
  # Clone GoldenCheetah
  - git clone --depth 1 -b $BRANCH git://github.com/GoldenCheetah/GoldenCheetah.git $BRANCH
  - cd $BRANCH
#  - git checkout `cat $TRAVIS_BUILD_DIR/commit`
#  - sh $TRAVIS_BUILD_DIR/git-info.sh
  # Copy in the libftd2xx libs/includes
  - mkdir D2XX
  - cp /Volumes/release/D2XX/Object/10.5-10.7/x86_64/libftd2xx.1.2.2.dylib D2XX
  - sudo cp /Volumes/release/D2XX/Object/10.5-10.7/x86_64/libftd2xx.1.2.2.dylib /usr/local/lib
  - cp /Volumes/release/D2XX/bin/*.h D2XX
  - sed -i "" "s|libftd2xx.dylib|@executable_path/../Frameworks/libftd2xx.1.2.2.dylib|" src/D2XX.cpp
  # Configure GoldenCheetah
  - cp qwt/qwtconfig.pri.in qwt/qwtconfig.pri
  - cp src/gcconfig.pri.in src/gcconfig.pri
  - /usr/local/opt/$QT_PATH/bin/lupdate src/src.pro
  - sed -i "" "s|#\(CONFIG += release.*\)|\1 static|" src/gcconfig.pri
  - sed -i "" "s|#\(SRMIO_INSTALL =.*\)|\1 /usr/local|" src/gcconfig.pri
  - sed -i "" "s|#\(D2XX_INCLUDE =.*\)|\1 ../D2XX|" src/gcconfig.pri
  - sed -i "" "s|#\(D2XX_LIBS    =.*\)|\1 -L../D2XX -lftd2xx.1.2.2|" src/gcconfig.pri
  - sed -i "" "s|#\(LIBOAUTH_INSTALL =.*\)|\1 /usr/local|" src/gcconfig.pri
  - sed -i "" "s|#\(LIBOAUTH_LIBS    =.*\)|\1 -L/usr/local/lib -loauth|" src/gcconfig.pri
  - sed -i "" "s|#\(QWT3D_INSTALL =.*\)|\1 /usr/local|" src/gcconfig.pri
  - sed -i "" "s|#\(QWT3D_INCLUDE =.*\)|\1 /usr/local/include/qwtplot3d-$QT|" src/gcconfig.pri
  - sed -i "" "s|#\(QWT3D_LIBS    =.*\)|\1 -lqwtplot3d-$QT|" src/gcconfig.pri
  - sed -i "" "s|#\(ICAL_INSTALL =.*\)|\1 /usr/local|" src/gcconfig.pri
  - sed -i "" "s|#\(ICAL_LIBS    =.*\)|\1 -lical|" src/gcconfig.pri
  - sed -i "" "s|#\(LIBUSB_INSTALL =\).*|\1 /usr/local|" src/gcconfig.pri
  - sed -i "" "s|#\(LIBUSB_LIBS    =.*\)|\1 -lusb|" src/gcconfig.pri
  - sed -i "" "s|#\(KML_INSTALL =.*\)|\1 /usr/local|" src/gcconfig.pri
  - sed -i "" "s|#\(KML_LIBS    =.*\)|\1 -lkmldom -lkmlconvenience -lkmlengine -lkmlbase|" src/gcconfig.pri
  - sed -i "" "s|#\(CLUCENE_INCLUDE =\).*|\1 /usr/local/lib|" src/gcconfig.pri
  - sed -i "" "s|#\(CLUCENE_LIBS    =\).*|\1 -lclucene-core -lclucene-shared|" src/gcconfig.pri
  - sed -i "" "s|#\(CONFIG += link_pkgconfig\)|\1|" src/gcconfig.pri
  - sed -i "" "s|#\(PKGCONFIG = .*\)|\1 oauth libical clucene libusb|" src/gcconfig.pri
  - cd ..
  
script:
  - cd $BRANCH
  # Qt4
  #- /usr/local/bin/qmake -makefile -spec unsupported/macx-clang -recursive CONFIG+=release CONFIG+=static QMAKE_CXXFLAGS_WARN_ON+=-Wno-unused-private-field
  # Qt5
  - /usr/local/opt/$QT_PATH/bin/qmake -makefile -recursive QMAKE_CXXFLAGS_WARN_ON+=-Wno-unused-private-field
  - make qmake_all 
  - make -j4 sub-qwt --silent
  - make -j4 sub-src

after_success:
  - cd src
  - ls -laR GoldenCheetah.app
  - sh $TRAVIS_BUILD_DIR/check-gc.sh
  - /usr/local/opt/$QT_PATH/bin/macdeployqt GoldenCheetah.app -verbose=2 -dmg
  - brew remove $QT
  - hdiutil mount GoldenCheetah.dmg
  - cd /Volumes/GoldenCheetah
  - ls -laR GoldenCheetah.app
  - GoldenCheetah.app/Contents/MacOS/GoldenCheetah --help
