os:
 - osx

env:
  
before_install:
  - brew update
  - brew update
  - brew install zlib
  - brew install --verbose https://raw.githubusercontent.com/gcoco/CI-for-GoldenCheetah/master/libkml.rb

script:
  - ls -laR /usr/local/
