language: gcc

before_install:
  - export TGT='x86_64-w64-mingw32.shared'
  - export MXE_DIR=~/tmp/mxe
  - rm -rf $MXE_DIR
  - git clone --depth=1 https://github.com/mxe/mxe.git $MXE_DIR
  
script:
  - make -C $MXE_DIR MXE_TARGETS="$TGT" gcc
  
after_success:
  - ls -laR $MXE_DIR
